"""Add depthead and org indexes

Revision ID: 1cf5a5edbfea
Revises: 
Create Date: 2025-06-17 09:48:10.725062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1cf5a5edbfea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """
    Create indexes to speed up Dept→Head and Employee lookups.
    """
    op.create_index(
        'ix_dept_head_lookup',
        'departments',
        ['department_head_id'],
    )
    op.create_index(
        'ix_dept_org',
        'departments',
        ['organization_id', 'id'],
        unique=False,
    )
    op.create_index(
        'ix_emp_org_head',
        'employees',
        ['organization_id', 'id'],
        unique=False,
    )


def downgrade() -> None:
    """
    Drop the indexes added in upgrade().
    """
    op.drop_index('ix_emp_org_head', table_name='employees')
    op.drop_index('ix_dept_org', table_name='departments')
    op.drop_index('ix_dept_head_lookup', table_name='departments')

# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_index('ix_superadmin_sessions_id', table_name='superadmin_sessions')
#     op.drop_table('superadmin_sessions')
#     op.drop_index('ix_daily_check_log_id', table_name='daily_check_log')
#     op.drop_table('daily_check_log')
#     op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
#     op.drop_table('apscheduler_jobs')
#     op.drop_index('ix_bulk_upload_errors_id', table_name='bulk_upload_errors')
#     op.drop_table('bulk_upload_errors')
#     op.drop_index('ix_employee_dynamic_data_id', table_name='employee_dynamic_data')
#     op.drop_table('employee_dynamic_data')
#     op.drop_table('super_admins')
#     op.drop_table('refresh_tokens')
#     # ### end Alembic commands ###
# def upgrade() -> None:
#     """
#     Create indexes to speed up Dept→Head and Employee lookups.
#     Uses CONCURRENTLY to avoid locking large tables in production.
#     """
#     op.create_index(
#         'ix_dept_head_lookup',
#         'departments',
#         ['department_head_id'],
#         # postgresql_concurrently=True,
#     )
#     op.create_index(
#         'ix_dept_org',
#         'departments',
#         ['organization_id', 'id'],
#         unique=False,
#         # postgresql_concurrently=True,
#     )
#     op.create_index(
#         'ix_emp_org_head',
#         'employees',
#         ['organization_id', 'id'],
#         unique=False,
#     )
#     op.create_index(
#         'ix_dept_org',
#         'departments',
#         ['organization_id', 'id'],
#         unique=False,
#         postgresql_concurrently=True,
#     )
#     op.create_index(
#         'ix_emp_org_head',
#         'employees',
#         ['organization_id', 'id'],
#         unique=False,
#         postgresql_concurrently=True,
#     )

# def downgrade() -> None:
#     """
#     Drop the indexes added in upgrade().
#     Uses CONCURRENTLY to avoid locking.
#     """
#     op.drop_index('ix_emp_org_head', table_name='employees')
#     op.drop_index('ix_dept_org', table_name='departments')
#     op.drop_index('ix_dept_head_lookup', table_name='departments')
#     op.drop_index('ix_dept_org', table_name='departments', postgresql_concurrently=True)
#     op.drop_index('ix_dept_head_lookup', table_name='departments', postgresql_concurrently=True)


# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('refresh_tokens',
#     sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
#     sa.Column('superadmin_id', sa.UUID(), autoincrement=False, nullable=False),
#     sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
#     sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
#     sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
#     sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
#     sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
#     sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['superadmin_id'], ['super_admins.id'], name='refresh_tokens_superadmin_id_fkey', ondelete='CASCADE'),
#     sa.PrimaryKeyConstraint('id', name='refresh_tokens_pkey'),
#     sa.UniqueConstraint('token', name='refresh_tokens_token_key')
#     )
#     op.create_table('super_admins',
#     sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
#     sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
#     sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
#     sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
#     sa.Column('security_key_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
#     sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
#     sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
#     sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
#     sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
#     sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
#     sa.PrimaryKeyConstraint('id', name='super_admins_pkey'),
#     sa.UniqueConstraint('email', name='super_admins_email_key'),
#     sa.UniqueConstraint('username', name='super_admins_username_key')
#     )
#     op.create_table('employee_dynamic_data',
#     sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=False),
#     sa.Column('data_category', sa.VARCHAR(), autoincrement=False, nullable=False),
#     sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
#     sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
#     sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
#     sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
#     sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
#     sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='employee_dynamic_data_employee_id_fkey', ondelete='CASCADE'),
#     sa.PrimaryKeyConstraint('id', name='employee_dynamic_data_pkey')
#     )
#     op.create_index('ix_employee_dynamic_data_id', 'employee_dynamic_data', ['id'], unique=False)
#     op.create_table('bulk_upload_errors',
#     sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
#     sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=False),
#     sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
#     sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
#     sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
#     sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
#     sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
#     sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='bulk_upload_errors_organization_id_fkey', ondelete='CASCADE'),
#     sa.PrimaryKeyConstraint('id', name='bulk_upload_errors_pkey')
#     )
#     op.create_index('ix_bulk_upload_errors_id', 'bulk_upload_errors', ['id'], unique=False)
#     op.create_table('apscheduler_jobs',
#     sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
#     sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
#     sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
#     sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
#     )
#     op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
#     op.create_table('daily_check_log',
#     sa.Column('check_date', sa.DATE(), autoincrement=False, nullable=False),
#     sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
#     sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
#     sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
#     sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
#     sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
#     sa.PrimaryKeyConstraint('id', name='daily_check_log_pkey'),
#     sa.UniqueConstraint('check_date', name='uq_daily_check_date')
#     )
#     op.create_index('ix_daily_check_log_id', 'daily_check_log', ['id'], unique=False)
#     op.create_table('superadmin_sessions',
#     sa.Column('uuid', sa.VARCHAR(), autoincrement=False, nullable=False),
#     sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
#     sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
#     sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
#     sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
#     sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
#     sa.PrimaryKeyConstraint('uuid', 'id', name='superadmin_sessions_pkey')
#     )
#     op.create_index('ix_superadmin_sessions_id', 'superadmin_sessions', ['id'], unique=False)
#     # ### end Alembic commands ###
